
export default {
  SOCKET_OPEN: 'SOCKET_OPEN',
  SOCKET_CLOSE: 'SOCKET_CLOSE',
  USERS_UPDATE: 'USERS_UPDATE',
  USER_CHANGE: 'USER_CHANGE',
  TEXT_UPDATE: 'TEXT_UPDATE',
  SEND_MSG: 'SEND_MSG',
  UPDATE_HISTORY: 'UPDATE_HISTORY',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
};